esig/dss

- dss-document/src/main/java/eu/europa/ec/markt/dss/validation102853/cades/CAdESSignature.java
Validating XAdES signature created with expired certificate results in indication INDETERMINATE and subindication OUT_OF_BOUNDS_NO_POE.
Simple report contains:
```
<Indication>INDETERMINATE</Indication>
<SubIndication>OUT_OF_BOUNDS_NO_POE</SubIndication>
<Error NameId="BBB_XCV_ICTIVRSC_ANS" NotAfter="2014-07-04T11:02:03Z" NotBefore="2013-07-04T11:02:03Z">The current time is not in the validity range of the signer's certificate.</Error>
<Warning NameId="LABEL_TINTWS">Additional assurance on the signing time may be needed to prove the validity of the signature.</Warning>
```
This is completely clear, because there was no timestamp. But...
Using the same file and certificate to create CAdES signature and then validating it results in indication INVALID and subindication HASH_FAILURE.
``` …
```
> Use public key instead of certificate to verify CAdES signature integrity

- dss-spi/src/main/java/eu/europa/esig/dss/XPathQueryHolder.java
- dss-xades/src/main/java/eu/europa/esig/dss/xades/validation/XAdESSignature.java
- dss-xades/src/test/java/eu/europa/esig/dss/xades/validation/XAdESValidationTest.java
- dss-xades/src/test/resources/validation/valid-xades.xml
This modification fixes setting signature policy URI to XAdES signature object when parsing and validating XAdES signature structure.
The element that is included in parsing XAdES signature is `SPURI` within the signature policy ID element (all other elements are already being properly parsed):
`SignaturePolicyId/SigPolicyQualifiers/SigPolicyQualifier/SPURI`
```xml
<xades:SignedSignatureProperties>
<xades:SignaturePolicyIdentifier>
<xades:SignaturePolicyId>
<xades:SigPolicyQualifiers>
<xades:SigPolicyQualifier>
<xades:SPURI>http://spuri.test</xades:SPURI>
</xades:SigPolicyQualifier>
</xades:SigPolicyQualifiers>
</xades:SignaturePolicyId>
</xades:SignaturePolicyIdentifier>
</xades:SignedSignatureProperties>
```
As a TDD enthusiast, I added a unit test so it would be visible what got fixed. …
> Fixed setting xades signature policy uri when parsing signature structure

- dss-asic/src/main/java/eu/europa/esig/dss/asic/signature/ASiCService.java
- dss-asic/src/test/java/eu/europa/esig/dss/asic/signature/asice/ASiCESignatureFilenameTest.java
This modification fixes setting signature filename when creating asic containers. Previously the `signatureFileName` parameter was not used correctly.
There was also an exception when a container was signed twice. The following exceptions were thrown when a container was signed twice:
```
eu.europa.esig.dss.DSSException: java.util.zip.ZipException: duplicate entry: META-INF/null
at eu.europa.esig.dss.asic.signature.ASiCService.createZipEntry(ASiCService.java:382)
at eu.europa.esig.dss.asic.signature.ASiCService.buildXAdES(ASiCService.java:725)
at eu.europa.esig.dss.asic.signature.ASiCService.storesSignature(ASiCService.java:398)
at eu.europa.esig.dss.asic.signature.ASiCService.buildASiCContainer(ASiCService.java:298)
at eu.europa.esig.dss.asic.signature.ASiCService.signDocument(ASiCService …
```
> Fixed setting signature filename when creating an asic container

- dss-service/src/main/java/eu/europa/esig/dss/client/http/commons/CommonsDataLoader.java
This modification fixes setting connection timeout on the `CommonsDataLoader` and all the derived classes.
Previously the data loader connection timeout setting did not have any effect.
> Fixed setting connection timeout on data loader

- dss-asic/src/main/java/eu/europa/esig/dss/asic/signature/ASiCService.java
This modification fixes setting encryption algorithm for asic containers. 
Previously the `encryptionAlgorithm` parameter did not have any effect. It is now possible to use other encryption algorithms instead of the default RSA, for example elliptic curves.
> Fixed setting encryption algorithm for asic containers

- dss-spi/src/main/java/eu/europa/esig/dss/x509/OCSPToken.java
This modification fixes handling OCSP revocation when an OCSP response doesn't contain a reason. In that case the 'unspecified' reason is used.
Previously when an OCSP response did not contain a reason, then an exception was thrown.
> Fixed handling OCSP revocation when reason is not given

- dss-xades/src/main/java/eu/europa/esig/dss/xades/validation/XAdESSignature.java
This modification reduces stack trace logging if there are any XAdES signature validation errors.
The log files would otherwise get filled with too much stack trace information.
> Reduced exception stack trace logging for xades signature validation

- dss-pades/src/test/java/eu/europa/esig/dss/pades/TwoPAdESSigniatureMustHaveDifferentIdTest.java
This modification fixes Java 6 support by replacing empty diamond operator <> by generics <String>. Diamond operators were added to Java 7.
We don't need Java 6 support, but somehow it broke the build anyway.
> Fixed Java 6 support, the diamond operator <>

- dss-model/src/main/java/eu/europa/esig/dss/tsl/ServiceInfoStatus.java
This modification makes ServiceInfoStatus class serializable. This is needed for serializing TSL.
> Made ServiceInfoStatus serializable

- dss-tsl-validation/src/main/java/eu/europa/esig/dss/tsl/service/TSLValidationJob.java
This change fixes a small bug that was introduced in DSS-883 (revalidating TSLs).
The problem is that when TSL signature check is turned off (checkTSLSignatures=false), then it still validates TSL, but sometimes we don't want to validate TSL (in some test cases).
This is fixed in the branch 4.7.x
Regards
> Fixed skipping TSL validation when LOTL has changed but validation is turned off

- dss-xades/src/main/java/eu/europa/esig/dss/xades/signature/DSSSignatureUtils.java
- dss-xades/src/test/java/eu/europa/esig/dss/xades/encoding/EncodingXMLTest.java
This change adds support to CVC concatenated signatures (in addition to ASN.1 encoded signatures).
Because CVC does not follow a structure like ASN.1, then I couldn't find a way to determine if a signature is definitely CVC or not. CVC signature bytes are simply concatenated. It is possible to check if the signature is ASN.1 encoded.
The fix origins from https://esig-dss.atlassian.net/browse/DSS-801
Estonian Mobile ID ECDSA signatures are encoded in CVC.
Regards
> Support for CVC concatenated signatures

- dss-cades/src/main/java/eu/europa/esig/dss/cades/signature/CAdESSignatureExtension.java
This change fixes an issue that has been observed when trying to validate PAdES signatures with timestamp tokens generated with SD-DSS in [ETSI conformance checker plugtests](http://signatures-conformance-checker.etsi.org).
Due to an empty set of unsigned attributes, the validator complains: 
https://www.dropbox.com/s/8ytbejijoks0lyu/Screenshot%202016-11-15%2010.44.23.png?dl=0
The error message expects there to be one or more values in the attribute map so this fix simply sets the unsigned attributes to `null` if empty and it validates successfully.
This seems similar to what was fixed in https://github.com/esig/dss/commit/4878d5fc33eb49e1a09d572b46034572a60e5cec
Hope this helps.
> Do not add empty unsigned attributes to timestamp token

- dss-pades/src/main/java/eu/europa/esig/dss/pades/signature/visible/ImageTextWriter.java
Hello,
I changed BufferedImage type in method:
ImageTextWriter.createTextImage
From BufferedImage.TYPE_INT_ARGB to BufferedImage.TYPE_INT_RGB
It's because after applying a visible signature on a PDF/A doc, the PDF/A  doc then not confrom with the conformance.
> Fix visible signature pdfa

- dss-spi/src/main/java/eu/europa/esig/dss/DSSUtils.java
Hi @pvandenbroucke 
We found a bug when trying to use DSSUtils to load certificates on a concurrent process (API).
Basically the `loadCertificates(InputStream is)` was returning more than one certificate sometimes making the `loadCertificate(final InputStream inputStream)` to fail the test `if (certificates.size() == 1)`.
At first glance everything was fine but we found out that storing a static CertificateFactory was the reason. So the fix was to use the `CertificateFactory.getInstance("X.509", BouncyCastleProvider.PROVIDER_NAME)` when needed instead of getting it from the static property.
FYI: @davydsantos
> On DSSUtils Instead a static CertificateFactory started using CertificateFactory.getInstance()

- dss-spi/src/main/java/eu/europa/esig/dss/tsl/CertSubjectDNAttributeCondition.java
- dss-spi/src/main/java/eu/europa/esig/dss/tsl/CompositeCondition.java
- dss-spi/src/main/java/eu/europa/esig/dss/tsl/ExtendedKeyUsageCondition.java
- dss-spi/src/main/java/eu/europa/esig/dss/tsl/KeyUsageCondition.java
- dss-spi/src/main/java/eu/europa/esig/dss/tsl/PolicyIdCondition.java
This adds getter methods to the TSL condition subtypes, cf. [DSS-1436](https://ec.europa.eu/cefdigital/tracker/browse/DSS-1436).
I also added a null check to the constructor of KeyUsageCondition to guarantee a non-null KeyUsageBit.
> TSL condition getters

- dss-service/src/main/java/eu/europa/esig/dss/client/http/commons/FileCacheDataLoader.java
isExpired check was missing for the FileCacheDataLoader post-request.
> fix to let cache expire also for POST requests

- dss-diagnostic-jaxb/src/main/java/eu/europa/esig/dss/jaxb/diagnostic/XmlRevocation.java
- dss-diagnostic-jaxb/src/main/resources/xsd/DiagnosticData.xsd
- dss-document/src/main/java/eu/europa/esig/dss/validation/CertificateVerifier.java
- dss-document/src/main/java/eu/europa/esig/dss/validation/CommonCertificateVerifier.java
- dss-document/src/main/java/eu/europa/esig/dss/validation/DiagnosticDataBuilder.java
Hi Pierrick,
In the following our suggestion to include the Revocation-data optionally in the DiagnosticData (Base64 encoded).
I hope this is ok to include in 5.4?
Regards
> add raw Revocation Values to diagnostic data (optionally)

- dss-reports/src/main/java/eu/europa/esig/dss/validation/reports/wrapper/CertificateWrapper.java
Certificate wrapper incorrectly returns isRevoked value.
(**status** field needs to be interpreted as: true if valid, false if revoked/onhold)
> Bug fix: certificate wrapper isRevoked implementation

- dss-pades-openpdf/src/main/java/eu/europa/esig/dss/pdf/openpdf/ITextPDFSignatureService.java
- dss-pades-pdfbox/src/main/java/eu/europa/esig/dss/pdf/pdfbox/PdfBoxSignatureService.java
This fixes [DSS-1601](https://ec.europa.eu/cefdigital/tracker/browse/DSS-1601), allowing the use of custom PDF signature drawers with DSS' existing PDF signature service implementations.
> [DSS-1601] Set access modifier of PDFSignatureService implementations to public

- dss-cades/src/main/java/eu/europa/esig/dss/cades/signature/CAdESLevelBaselineLT.java
- dss-xades/src/main/java/eu/europa/esig/dss/xades/signature/XAdESLevelBaselineT.java
Fixes [DSS-1581](https://ec.europa.eu/cefdigital/tracker/projects/DSS/issues/DSS-1581).
This change unifies the behaviour during validation.
XAdES and CAdES signatures behave differently from PAdeES signatures.
All signature types now use the validation pool from the CertificateVerifier instead of creating a new, empty instance.
> Get certificate validation pool from CertificateVerifier.

- dss-cades/src/main/java/eu/europa/esig/dss/cades/signature/CAdESLevelBaselineB.java
As per Section 3.9.1  Signature policy Identifier from RFC3126:
This document specifies the following qualifiers:
*  spuri: This contains the web URI or URL reference to the
signature policy
*  spUserNotice: This contains a user notice which should be
displayed whenever the signature is validated.
-- sigpolicyQualifierIds defined in this document
SigPolicyQualifierId ::=  OBJECT IDENTIFIER
id-spq-ets-uri OBJECT IDENTIFIER ::= { iso(1)
member-body(2) us(840) rsadsi(113549) pkcs(1) pkcs9(9)
smime(16) id-spq(5) 1 }
SPuri ::= IA5String
But the implementation was incorrectly using UTF8String
Signed-off-by: Bruno Melo <brunosm@tst.jus.br>
> Fixes id-spq-ets-uri encoding from UTF8String to IA5String

- dss-xades/src/main/java/eu/europa/esig/dss/xades/XAdESSignatureParameters.java
- dss-xades/src/main/java/eu/europa/esig/dss/xades/signature/EnvelopedSignatureBuilder.java
- dss-xades/src/main/java/eu/europa/esig/dss/xades/signature/XAdESSignatureBuilder.java
- dss-xades/src/test/java/eu/europa/esig/dss/xades/signature/XAdESLevelBEnvelopedWithXPathPlacementAfterRootNodeTest.java
- dss-xades/src/test/java/eu/europa/esig/dss/xades/signature/XAdESLevelBEnvelopedWithXPathPlacementAfterTest.java
- dss-xades/src/test/java/eu/europa/esig/dss/xades/signature/XAdESLevelBEnvelopedWithXPathPlacementFirstChildTest.java
- dss-xades/src/test/java/eu/europa/esig/dss/xades/signature/XAdESLevelBEnvelopedWithXPathPlacementNoneTest.java
In the [OASIS Digital Signature Service Protocol](https://docs.oasis-open.org/dss-x/dss-core/v2.0/dss-core-v2.0.html) there is a component called SignaturePlacement (chapter 4.4.18). It is used to request an enveloped XAdES signature for a document with the option to add an XPath to specify where the signature element is to appear within the signed document. So far this is supported by DSS. However, SignaturePlacement further distinguishes between two cases, namely "XPathAfter" and "XPathFirstChildOf". Depending on which is used the signed document should look different for the same XPath. For the first case, the signature element should appear as next sibling of the element referenced by the XPath, whereas for the second it should be inserted as its first child. Currently DSS inserts the …
> Feature: Signature placement in XAdES according to OASIS DSS standard

- README.md
Fixing in the link on the develop branch.
> Fixing the link to CEF Digital repository in README file

- pom.xml
Motivations:
* Keep the technical stack up-to-date
Modifications:
* Update maven-javadoc-plugin version from 3.1.1 to 3.2.0
Results:
* No functional impact
> Update maven-javadoc-plugin version from 3.1.1 to 3.2.0

- dss-pades-pdfbox/src/main/java/eu/europa/esig/dss/pdf/pdfbox/visible/nativedrawer/NativePdfBoxVisibleSignatureDrawer.java
- dss-pades-pdfbox/src/main/java/eu/europa/esig/dss/pdf/pdfbox/visible/nativedrawer/SignatureFieldDimensionAndPosition.java
- dss-pades-pdfbox/src/main/java/eu/europa/esig/dss/pdf/pdfbox/visible/nativedrawer/SignatureFieldDimensionAndPositionBuilder.java
This PR addresses the issues raised in both DSS-2437 and DSS-2438. It then goes further and removes a lot of redundant calculations in `SignatureFieldDimensionAndPositionBuilder`.
The last commit of the bunch moves some code from `SignatureFieldDimensionAndPosition` into `SignatureFieldDimensionAndPositionBuilder`. At this point, that code was only being set up and called by `SignatureFieldDimensionAndPositionBuilder` and so I felt its purpose was being obfuscated by keeping it where it was. This is however a non-essential change so feel free to ignore that particular commit if you feel it is an overreach.
> DSS-2437, DSS-2438: Simplify native pdf drawer

- dss-pades-pdfbox/src/main/java/eu/europa/esig/dss/pdf/pdfbox/visible/nativedrawer/NativePdfBoxVisibleSignatureDrawer.java
- dss-pades-pdfbox/src/main/java/eu/europa/esig/dss/pdf/pdfbox/visible/nativedrawer/SignatureFieldDimensionAndPosition.java
- dss-pades-pdfbox/src/main/java/eu/europa/esig/dss/pdf/pdfbox/visible/nativedrawer/SignatureFieldDimensionAndPositionBuilder.java
Encapsulates the  padding calculations of the native PDFBox drawer in `SignatureFieldDimensionAndPositionBuilder` to reduce repetition and to make the code easier to understand.
More details in JIRA ticket [DSS-2458](https://ec.europa.eu/cefdigital/tracker/browse/DSS-2458).
> DSS-2458: encapsulate padding calculations

- dss-pades-pdfbox/src/test/java/eu/europa/esig/dss/pades/signature/visible/PdfBoxTextFitterTest.java
- dss-pades/src/main/java/eu/europa/esig/dss/pdf/visible/SignatureFieldDimensionAndPositionBuilder.java
- dss-pades/src/main/java/eu/europa/esig/dss/pdf/visible/TextFitter.java
As described in [DSS-2497](https://ec.europa.eu/cefdigital/tracker/browse/DSS-2497), this PR implements a mechanism to auto-fit the signature text to the available space in the signature box.
> DSS-2497: auto-fit text to the existing space in signature

- dss-pades-pdfbox/src/main/java/eu/europa/esig/dss/pdf/pdfbox/PdfBoxSignatureService.java
- dss-pades/src/main/java/eu/europa/esig/dss/pades/PAdESSignatureParameters.java
- dss-pades/src/test/java/eu/europa/esig/dss/pades/signature/visible/suite/PAdESLevelBCertificationTest.java
By a PDF specification It is able to add a signing application name into Sig dictionary.
https://www.pdfa.org/norm-refs/SigBuildDict.pdf
This PR adds simple support for adding signing app name into pades signature.
Unfortunately ONLY pdfbox supports methods to add this property out of the box.
OpenPdf does not support it (requires additional support on their side).
reported as a new feature request
https://ec.europa.eu/cefdigital/tracker/browse/DSS-2692
> PAdES: signing app name for pades signatures
